version: '3.8'

services:
  momsittermysql57:
    platform: linux/x86_64
    container_name: capsule-local-mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: capsule
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    volumes:
      - ./init:/docker-entrypoint-initdb.d
