# fly.toml file generated for hanghae-capsule-backend on 2023-03-23T21:48:45+09:00

app = "hanghae-capsule-backend"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "nrt"
processes = []

[env]
  SPRING_PROFILES_ACTIVE = "prod"
  AWS_DB_URL = "$[secrets.AWS_DB_URL]"
  AWS_DB_USERNAME = "$[secrets.AWS_DB_USERNAME]"
  AWS_DB_PASSWORD = "$[secrets.AWS_DB_PASSWORD]"
  CAPSULE_EMAIL = "$[secrets.CAPSULE_EMAIL]"
  CAPSULE_PASSWORD = "$[secrets.CAPSULE_PASSWORD]"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
