spring:
  datasource:
    url: jdbc:h2:mem:capsule-testdb

---
spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
